"""
Django settings for dailyfresh project.

Generated by 'django-admin startproject' using Django 1.8.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

# 【新加】 将apps目录加入搜索中
import sys

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# 【新加】将apps目录加入搜索中
sys.path.insert(0, os.path.join(BASE_DIR, 'apps'))



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'eg)jj@ke@7-&(kw06@$_+%fa*ztd-#db-^s*xxr6q3q!llqu*7'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 【新加】应用模块
    'tinymce', # 富文本编辑器
    'haystack', # 全文检索框架
    'user', # 用户模块
    'cart', # 购物车模块
    'goods', # 商品模块
    'order', # 订单模块
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'dailyfresh.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # 【新加】将templates加入路径
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'dailyfresh.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        # 【新加】修改数据库为mysql mysql 用的本地
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'dailyfresh',
        'USER': 'root',
        'PASSWORD': 'tianshi2019',
        'HOST': 'localhost',
        'PORT': 3306,
        # django 2.0 可以直接设置数据隔离 'isolation_level':'read committed'
    }
}

# django 认证系统使用的模型类,
# mysql数据库中默认有user数据库，如果不认证，就会使用系统的user表
AUTH_USER_MODEL = 'user.User'


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
# 指定收集静态文件的路径
STATIC_ROOT = '/var/www/dailyfresh/static'

# 富文本编辑器配置
TINYMCE_DEFAULT_CONFIG = {
    'theme': 'advanced',
    'width': 600,
    'height': 400,
}


# 以下内容为邮箱服务器设置
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.163.com'
EMAIL_PORT = 25
#发送邮件的邮箱
EMAIL_HOST_USER = '15577008324@163.com'
#在邮箱中设置的客户端授权密码
EMAIL_HOST_PASSWORD = 'tianxia2019'
#收件人看到的发件人
EMAIL_FROM = '天天生鲜<15577008324@163.com>'


# django缓存配置，django-redis
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/9",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

# session存储在redis中
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"


# 重新配置登录url地址
LOGIN_URL = '/user/login'



# 设置django文件储存类
# DEFAULT_FILE_STORAGE = 'utils.fdfs.storage.FDFSStorage'

# 七牛云配置
# access_key = 'rUo3vBsGl2Lrf-a9MFSb_LYx3QMbZUwuQPmZKfJz'
# secret_key = 'I8mKskRL-69QMhqexXjKYguKK-Ffv-nnhCVCL2PO'
QINIU_ACCESS_KEY = 'rUo3vBsGl2Lrf-a9MFSb_LYx3QMbZUwuQPmZKfJz'
QINIU_SECRET_KEY = 'I8mKskRL-69QMhqexXjKYguKK-Ffv-nnhCVCL2PO'
QINIU_BUCKET_NAME = 'python_study'
QINIU_BUCKET_DOMAIN = 'pww211o23.bkt.clouddn.com'
QINIU_SECURE_URL = False


# PREFIX_URL = 'http://'
# # 文件系统更改
# MEDIA_URL = PREFIX_URL + QINIU_BUCKET_DOMAIN + 'media/'
# # MEDIA_ROOT = os.path.join(BASE_DIR, 'media').replace("\\", "/")
# MEDIA_ROOT = 'media/'

# 七牛云配置
DEFAULT_FILE_STORAGE = 'qiniustorage.backends.QiniuStorage'


# 全文检索框架的配置
HAYSTACK_CONNECTIONS = {
    'default': {
        #使用whoosh引擎
        # 如果使用jieba分词包，则需要使用whoosh_cn_backend
        # whoosh_cn_backend怎么来的？是先复制了whoosh_backend，然后对其修改
        # 'ENGINE': 'haystack.backends.whoosh_backend.WhooshEngine',
        'ENGINE': 'haystack.backends.whoosh_cn_backend.WhooshEngine',
        # 注意！！，修改whoosh_cn_backend配置后，需要重新在终端生成 python3 manage.py rebuild_index
        #索引文件路径
        'PATH': os.path.join(BASE_DIR, 'whoosh_index'),
    }
}

#当添加、修改、删除数据时，自动生成索引
HAYSTACK_SIGNAL_PROCESSOR = 'haystack.signals.RealtimeSignalProcessor'


# 指定搜索结果的每个页面显示商品数量
HAYSTACK_SEARCH_RESULTS_PER_PAGE=1

